export const translatePokemonTypeNames: {[key: string]: string} = {
    grass: "grama",
    poison: "veneno",
    fire: "fogo",
    water: "água",
    flying: "voador",
    electric: "elétrico",
    ground: "terra",
    fighting: "lutador",
    rock: "pedra",
    psychic: "psíquico",
    ice: "gelo",
    bug: "inseto",
    ghost: "fantasma",
    steel: "ferro",
    fairy: "fada",
    normal: "normal",
  };